project:
  title: "quarto-doc-test"
  output-dir: "docs"


toc: true
number-sections: true

format:
  html:
    toc: true
    toc-depth: 2
  pdf:
    toc: true
    include-in-header: "pre-tex/thai-preamble.tex"
    keep-tex: true
    linkcolor: Maroon